name: GhostBuster
main: com.splatage.ghostbuster.GhostBusterPlugin
version: "${version}"
api-version: '1.20'   # good for 1.20+; Paper tolerates forward on 1.21
folia-supported: true
description: Prunes ghost entity links to allow GC to reclaim retained objects.
author: splatage
commands:
  ghostbuster:
    description: GhostBuster admin commands
    usage: /ghostbuster <status|dryrun|prune <uuid>|scan>
permissions:
  ghostbuster.admin:
    default: op
